name: 'notion-clipper-archiver'
description: 'Archive notion web clipper data to json file'
author: 'RyoJerryYu'
branding:
  icon: bookmark
  color: gray-dark
inputs:
  database_id:
    required: true
    description: 'notion database id used for notion web clipper'
  notion_token:
    required: true
    description: 'notion token to access notion api'
  save_dir:
    required: true
    description: 'directory to save the json file'
  file_name:
    required: true
    description: 'name of the json file'
  contains_tags:
    required: false
    description: 'filter the notion web clipper data by tags'
  not_contains_tags:
    required: false
    description: 'filter the notion web clipper data by tags'
  need_content:
    required: false
    description: 'whether to include the content of the notion web clipper data'
    default: 'false'
outputs:
  save_path:
    description: 'saved json file path'
runs:
  using: 'node16'
  main: 'dist/index.js'
