name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          make build
      - run: | 
          npm run all
        env:
          INPUT_DATABASE_ID: ${{ secrets.INPUT_DATABASE_ID }}
          INPUT_NOTION_TOKEN: ${{ secrets.INPUT_NOTION_TOKEN }}
          INPUT_SAVE_DIR: ./results
          INPUT_FILE_NAME: res.json
          INPUT_NEED_CONTENT: false
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: notion_clipper_archiver
        with:
          database_id: ${{ secrets.INPUT_DATABASE_ID }}
          notion_token: ${{ secrets.INPUT_NOTION_TOKEN }}
          save_dir: ./results
          file_name: res.json
          need_content: true
          contains_tags: |
            ipfs
            Tool
          not_contains_tags: |
            Wasm

      - uses: actions/upload-artifact@v3
        with:
          name: results
          path: ${{ steps.notion_clipper_archiver.outputs.save_path }}

